train:
  _target_: src.datasets.SyntheticAVDataset
  dataset_length: 10
  audio_shape: [1024]
  video_shape: [768]
  limit: 10
val:
  _target_: src.datasets.SyntheticAVDataset
  dataset_length: 10
  audio_shape: [1024]
  video_shape: [768]
  limit: 10
