val:
  _target_: src.datasets.SyntheticAVDataset
  dataset_length: 16
  audio_shape: [1024]
  video_shape: [768]
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.SyntheticAVDataset
  dataset_length: 16
  audio_shape: [1024]
  video_shape: [768]
  instance_transforms: ${transforms.instance_transforms.inference}
