device: "auto"
train:
  - _target_: src.metrics.AccuracyMetric
    device: ${metrics.device}
    name: "Accuracy"
  - _target_: src.metrics.AUROCMetric
    device: ${metrics.device}
    name: "AUROC"
  - _target_: src.metrics.AveragePrecisionMetric
    device: ${metrics.device}
    name: "PRAUC"
inference:
  - _target_: src.metrics.AccuracyMetric
    device: ${metrics.device}
    name: "Accuracy"
  - _target_: src.metrics.PrecisionMetric
    device: ${metrics.device}
    name: "Precision"
  - _target_: src.metrics.RecallMetric
    device: ${metrics.device}
    name: "Recall"
  - _target_: src.metrics.F1Metric
    device: ${metrics.device}
    name: "F1"
  - _target_: src.metrics.AUROCMetric
    device: ${metrics.device}
    name: "AUROC"
  - _target_: src.metrics.AveragePrecisionMetric
    device: ${metrics.device}
    name: "PRAUC"
