_target_: src.model.GatedAVModel
audio_input_dim: ${audio_feature_dim}
video_input_dim: ${video_feature_dim}
embedding_dim: 256
hidden_dim: 256
dropout: 0.2
audio_input_type: features
video_input_type: features
fusion_type: gmu
fusion_kwargs: {}
