defaults:
  - baseline
  - override /model: audio_only_model
  - override /datasets: features_train_val
  - _self_

writer:
  run_name: audio_pretrain

datasets:
  train:
    label_mode: audio_fake
  val:
    label_mode: audio_fake

trainer:
  device_tensors: ["audio", "labels"]
  use_weighted_sampler: true
  monitor: "max val_AUROC"
