defaults:
  - model: gated_av_model
  - metrics: example
  - datasets: features
  - dataloader: av
  - transforms: av_identity
  - _self_

features_root: ???
dataset_root: ???
index_dir: ./data/indices/fakeavceleb
num_frames: 16
video_size: 224
audio_feature_dim: 1024
video_feature_dim: 768

inferencer:
  device_tensors: ["audio", "video", "labels"] # which tensors should be on device
  device: auto # device name or "auto"
  save_path: "saved/predictions"
  seed: 1
  from_pretrained: "saved/av_finetune/model_best.pth"
